name: s0lv1t
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager:
    git:
      url: https://github.com/leanflutter/window_manager.git
      ref: main
  fluent_ui:
    git: https://github.com/bdlukaa/fluent_ui.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
